version: '3'

services:
  magicmirror:
    image: karsten13/magicmirror:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
      - ./start_script.sh:/opt/magic_mirror/start_script.sh
      - /etc/localtime:/etc/localtime:ro
      - ./custom_translations.json:/opt/magic_mirror/translations/en.json
      - /mnt/chromeos/GoogleDrive/MyDrive/Newt_of_the_day:/opt/magic_mirror/modules/MMM-Random-local-image/Newt_of_the_day/
    restart: unless-stopped
    command: 
      - npm
      - run
      - server
    environment: 
      MM_SHOW_CURSOR: "true"
      TZ:  "America/Los_Angeles"
    env_file:
      - secrets.env
