version: '3'

services:
  magicmirror:
    image: karsten13/magicmirror:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
      - ./start_script.sh:/opt/magic_mirror/start_script.sh
    restart: unless-stopped
    command: 
      - npm
      - run
      - server
    environment: 
      MM_SHOW_CURSOR: "true"
    env_file:
      - secrets.env
