#!/bin/bash

mkdir -p "$HOME/scripts"
_log="$HOME/scripts/start.log"
if [[ ! -f "$HOME/magicmirror/run/docker-compose.yml" ]]; then
  source "/etc/os-release"
  [[ "$VERSION_CODENAME" == "buster" ]] && _dcfile="rpi_mmos.yml" || _dcfile="rpi.yml"
  cp -v "$HOME/magicmirror/run/$_dcfile" "docker-compose.yml" &>> $_log
  mkdir -p "$HOME/magicmirror/mounts"
else
  echo "docker-compose.yml exists" &>> $_log
fi

cd "$HOME/magicmirror/run"
# update git repo
git fetch
# start mm
docker-compose up -d &>> $_log
# pull newest docker image
docker-compose pull &>> $_log
# restart if image changed
docker-compose up -d &>> $_log
# delete old images
docker image prune -f &>> $_log
# disable wlan power save
sudo iw wlan0 set power_save off

sleep infinity
